# Generated by Django 3.1.7 on 2021-04-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Undefined', max_length=50),
        ),
    ]
