# Generated by Django 3.1.7 on 2021-04-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='published_date',
        ),
    ]
