# Generated by Django 3.1.7 on 2021-04-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('cast', models.ManyToManyField(to='app.Actor')),
                ('director', models.ManyToManyField(to='app.Director')),
                ('genre', models.ManyToManyField(to='app.Genre')),
                ('producer', models.ManyToManyField(to='app.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.ManyToManyField(to='app.Genre')),
                ('favorite_movies', models.ManyToManyField(related_name='user_favorite_movies', to='app.Movie')),
                ('movies_watched', models.ManyToManyField(related_name='user_watched_movies', to='app.Movie')),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_watch', models.ManyToManyField(related_name='user_wanttowatch_movies', to='app.Movie')),
            ],
        ),
    ]
