# Generated by Django 3.1.7 on 2021-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_movie_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
