# Generated by Django 3.2 on 2021-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210428_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='years_active',
            field=models.IntegerField(),
        ),
    ]
